apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: webookrepo/books
          env:
          - name: MONGODB_URI
            value: 'mongodb://books-mongodb-srv:27017/booksdb'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: books-srv
spec:
  selector:
    app: books
  ports:
    - name: books
      protocol: TCP
      port: 3000
      targetPort: 3000
